src/Entity/Form.php
<?php

namespace App\Entity;

use App\Repository\FormRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use EWZ\Bundle\RecaptchaBundle\Validator\Constraints as Recaptcha;

/**
 * @ORM\Entity(repositoryClass=FormRepository::class)
 */
class Form
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $prenom;

    /**
     * @ORM\Column(type="bigint")
     * @Assert\NotBlank
     * @Assert\Length(
     *       min = 10,
     *       max = 10
     * )
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Positive
     */
    private $quantite;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $nom_etablissement;
    
    /**
     * @Recaptcha\IsTrue
     */
    public $recaptcha;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNomEtablissement(): ?string
    {
        return $this->nom_etablissement;
    }

    public function setNomEtablissement(string $nom_etablissement): self
    {
        $this->nom_etablissement = $nom_etablissement;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }
}

templates/Body/connectAdmin.html.twig
{# templates/Body/connectAdmin.html.twig #}

<html lang="fr"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="../css/connect.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  

    <title>AgainstCOVID-19 - Espace administrateur</title>


  </head>

  <body class="text-center">
    <form method='POST' action='{{ path('connectAdminCheck') }}' class="form-signin">
      <h1 class="h1 mb-3 font-weight-normal">Bienvenue dans l'espace Administrateur</h1>
      <p class="h5 mb-3 font-weight-normal">Ici l'équipe de projet peut consulter beaucoup de choses et peut gérer vos demandes </p>
      <label for="inputPassword" class="sr-only">Password</label>
      <input name='password' type="password" id="inputPassword" class="form-control" placeholder="Mot-de-passe administrateur" required="">
      <button class="btn btn-lg btn-dark btn-block" type="submit">Se connecter</button>
      <p class="mt-5 mb-3">Oups... Vous vous êtes trompé de lien ?</p>
      <a class="badge badge-secondary" href="{{ path('homePage') }}">Cliquez ici pour retourner à la page d'accueil</a>
      <p class="mt-5 mb-3 text-muted">@2020 - AgainstCOVID-19</p>
    </form>
  

</body></html>

templates/Body/contactPage.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<!-- Compiled and minified CSS -->
	<link
	rel="stylesheet" href="{{ asset('css/contact.css') }}">
	<!-- Compiled and minified JavaScript -->
	<script src="{{ asset('js/jquery.js') }}"></script>
	<script src="{{ asset('js/map.js') }}"></script>
	<!--The callback parameter executes the initMap() function-->
	<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBoq3pqBB4rNSPZtWBmRH60T-T-CLr9qWE&callback=initMap"></script>

{% endblock %}

{% block body %}

	<div class='container-fluid'>

		<div class='row'>
            

			<!--<div class='col-2'></div>-->

			<div class='col-6 py-2'>

				<div class="card my-5" style="display: inline-block; width: 100%;">
					<div class="card-header h2">
						Nos Coordonnées
					</div>
					<ul class="list-group list-group-flush">
						<li class="list-group-item" style='font-size: 17px'><p class='h5'>Adresse : </p><p class='px-3 py-1'>Campus CESI Toulouse, Batiment Alpha, 16 Rue Magellan, 31670 Labège</p></li>
						<li class="list-group-item" style='font-size: 17px'><p class='h5'>N° Téléphone : </p><p class='px-3'> Gabriel RICARD : 0782360024 </br> Kevin BOURDEAU : 0644760951 </br> Corentin PAUGAM : 0695669002</p></li>
						<li class="list-group-item" style='font-size: 17px'><p class='h5'>E-mail : </p><a  class='px-3' href='mailto:gabriel.ricard@viacesi.fr'>gabriel.ricard@viacesi.fr</a></br><a  class='px-3' href='mailto:kevin.bourdeau@viacesi.fr'>kevin.bourdeau@viacesi.fr</a></br><a  class='px-3' href='mailto:corentin.paugam@viacesi.fr'>corentin.paugam@viacesi.fr</a></li>
					</ul>
				</div>

			</div>

			<div class='col-6'>
				<!--<h3>My Google Maps Demo</h3>-->
				<!--Element div de la map -->
				<div id="map"></div>
			</div>

		</div>

	</div>

{% endblock %}

templates/Body/formPage.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block stylesheets %}
	<!-- Compiled and minified JavaScript -->
	<script src="{{ asset('js/jquery.js') }}"></script>
	<script src="{{ asset('js/autocomplete.js') }}"></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBoq3pqBB4rNSPZtWBmRH60T-T-CLr9qWE&libraries=places"></script>

{% endblock %}

{% block body %}

	<div class='container py-5'>

		<hr class="featurette-divider">

		<div class='py-1'>

			<h2 class='text-center py-2'>
				Formulaire de demande
			</h2>

			<p class='px-4'>
				Ici vous pouvez rentrer toutes les informations nécessaires à votre demande. Veuillez vous assurer que tous les champs sont bien remplis et correspondent bien à vos coordonnées, ces données seront ensuite utilisées afin de vous recontacter et satisfaire votre demande.
			</p>

		</div>

		<hr class="featurette-divider">

		{# Affichage du formulaire avec les données entrées #}
		{{ form_start(form)}}

		{{ form_row(form.nom, {'label': 'Nom', 'attr': {'placeholder': 'Entrez votre nom'}})}}
		{{ form_row(form.prenom, {'label': 'Prénom', 'attr': {'placeholder': 'Entrez votre prénom'}})}}
		{{ form_row(form.nomEtablissement, {'label': 'Nom établissement', 'attr': {'placeholder': 'Entrez le nom de votre établissement'}})}}
		{{ form_row(form.tel, {'label': 'Numéro téléphone', 'attr': {'placeholder': 'Entrez votre numéro de téléphone'}})}}
		{{ form_row(form.email, {'label': 'Email', 'attr': {'placeholder': 'Entrez votre email'}})}}
		{{ form_row(form.quantite, {'label': 'Quantité', 'attr': {'placeholder': 'Entrez la quantité que vous voulez'}})}}
		{#Affichage du bouton valider  #}
		<input class='btn btn-dark btn-large btn-block py-3' value='Valider' type="submit" name="submitpost">

		{{ form_end(form)}}

		<hr class="featurette-divider">

	</div>


{% endblock %}

templates/Body/homePage.html.twig
{# templates/Body/homePage.html.twig #}

<main role="main">



<div style="margin-bottom: 3em" id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <div class="carousel-item active">
      <img class="d-block w-100" src="/image/carrousel1.jpg" alt="First slide">
      <div class="container">
              <div class="carousel-caption text-left carousel-container">
                <h1>A propos de nous</h1>
                <p>Étudiants à CESI, campus d’enseignement supérieur et de formation professionnelle, nous avons choisi de nous investir dans un projet qui aiderait à mettre en place les gestes barrières autour de Toulouse et lutter contre le COVID-19.</p>
                <p><a class="btn btn-lg btn-light" href="#LearnMore" role="button">En apprendre plus</a></p>
              </div>
            </div>
    </div>

    <div class="carousel-item">
      <img class="d-block w-100" src="/image/carrousel2.jpg" alt="Second slide">
      <div class="container">
              <div class="carousel-caption text-left  carousel-container">
                <h1>Le respirateur</h1>
                <p>La solution que nous proposons, est un masque de respirateur déployable rapidement pour les centres hospitaliers de Toulouse. Fabriqué dans notre campus en collaboration avec Décathlon.</p>
                <p><a class="btn btn-lg btn-light" href="{{ path('productPage') }}" role="button">Consulter la fiche produit</a></p>
              </div>
      </div>
    </div>

    <div class="carousel-item">
      <img class="d-block w-100" src="/image/carrousel3.jpg" alt="Third slide">
      <div class="container">
              <div class="carousel-caption text-left  carousel-container">
                <h1>Dans le besoin ?</h1>
                <p>Si vous travaillez dans un hôpital et pensez que ce masque pourrait vous être très utile en cette période sombre, nous vous proposons de formuler votre demande en ligne.</p>
                <p><a class="btn btn-lg btn-light" href="{{ path('demandePage') }}" role="button">Formuler votre demande</a></p>
              </div>
      </div>
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container marketing" id="LearnMore">

  <hr class="featurette-divider">


  <div class="row featurette" id="section1">
    <div class="col-md-7">
      <h2 class="featurette-heading">Qui sommes nous ?</h2>
      <p class="lead"> {{ s1 }} </p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" style="width: 500px; height: 500px;" src="/image/rs1.jpg" data-holder-rendered="true">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette" id="section2">
    <div class="col-md-5">
      <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" style="width: 500px; height: 500px;" src="/image/rs2.jpg" data-holder-rendered="true">
    </div>
    <div class="col-md-7">
      <h2 class="featurette-heading">Notre Projet</h2>
      <p class="lead"> {{ s2 }} </p>
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette" id="section3">
    <div class="col-md-7">
      <h2 class="featurette-heading">Notre Produit</h2>
      <p class="lead"> {{ s3 }} </p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" style="width: 500px; height: 500px;" src="/image/rs3.jpg" data-holder-rendered="true">
    </div>
  </div>

  <hr class="featurette-divider">

</div>

</main>

templates/Body/productPage.html.twig
{# templates/Body/productPage.html.twig #}

<main role="main">

    <div class="jumbotron">
        <div class="container">
           <h1 class="display-4">Besoin d'un respirateur déployable rapidement</h1>
           <p>
                Notre produit est préparé avec nos petits soins au fab-lab du CESI Labège, les pièces sont imprimées sur mesure en fonction de vos besoins.
            </p>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-1"></div>
            <div class="container col-lg py-5">
                <hr class="featurette-divider">
                <h2>Le masque</h2>
                <p>
                    Nous prenons appui sur un produit déjà existant, le masque de snorkeling en surface EASYBREATH conçu par Décathlon. Il s'agit d'un masque de plongée entièrement
                     impermeable, et permettant à l'utilisateur de respirer à la fois par la bouche et par le nez. Grâce à un partenariat avec Décathlon - Portet-sur-Garonne, nous 
                     avons la possibilité de les transformer en respirateur et de les mettre à disposition des hôpitaux au moindre coût.
                </p>
            </div>
            <div class="py-4">
                <img src="/image/masque.png" style="width: 700px">
            </div>
            <div class="col-1"></div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-1"></div>
            <div class="container col-lg py-5">
                <hr class="featurette-divider">
                <h2>La pièce qui change tout !</h2>
                <p>
                    Afin de transformer le produit original en respirateur, nous avons besoin d'une pièce qui pourrait connecter ce masque au dispositif de respiration. 
                    L'idée est née en Italie, un ingénieur italien a eu la bonne idée de changer l'embout de la maque, qui est censé sortir de l'eau et permettre de faire 
                    respirer son utilisateur. Cet embout est remplacé par une simple pièce imprimée par une imprimante 3D et qui par la suite permet le masque de se connecter au
                     dispositif.
                </p>
            </div>
            <div>
                <img src="/image/piece.jpg" style="width: 700px">
            </div>
            <div class="col-1"></div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-1"></div>
            <div class="container col-lg py-5">
                <hr class="featurette-divider">
                <h2>Un produit adaptatif ?</h2>
                <p>
                    Cette pièce est donc fabriquée par une imprimante 3D avec des matériaux d'impression impermeable. Dans le centre CESI Labège, 
                    nous avons la possibilité de créer une telle pièce grâce au multiple imprimante que nous possédons. Ce produit peut même être modifié par CAO par 
                    nos soins pour qu'il répond le mieux possible à vos besoins.
                </p>
            </div>
            <div>
                <img src="/image/ultimaker.jpg" style="width: 700px">
            </div>
            <div class="col-1"></div>
        </div>
    </div>



    <div class="container text-center  py-3">
        <hr class="featurette-divider">
        <h2>Vous êtes intéressé ?</h2>
        <p>
            Nous vous proposons de remplir un formulaire de demande, cette demande sera par la suite transmise à notre équipe de projet. Ainsi, nous vous recontacterons pour en savoir plus sur vos besoins et préparer une commandes pour dans les plus brefs délais.
        </p>
        <p>
            <a href="{{ path('demandePage') }}" class="btn btn-lg btn-secondary">Formuler une demande</a>
        </p>
    </div>

</main>

templates/Body/tableBottom.html.twig
{# templates/Body/tableBottom.html.twig #}

            </tbody>
        </table>
    </div>
</main>

templates/Body/tableRow.html.twig
{# templates/Body/tableRow.html.twig #}

                <tr>
                <th scope="row">{{ id }}</th>
                <td>{{ nom }}</td>
                <td>{{ prenom }}</td>
                <td>{{ nom_etablissement }}</td>
                <td>{{ tel }}</td>
                <td>{{ email }}</td>
                <td>{{ quantite }}</td>
                <td>{{ date }}</td>
                {% if status == 0 %}
                    <td>Non traité</td>
                {% else %}
                    <td>Traité</td>
                {% endif %}
                </tr>

templates/Body/tableTop.html.twig
{# templates/Body/tableTop.html.twig #}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<main role='main'>
    <div class='mx-5'>
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">#ID</th>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Nom établissement</th>
                <th scope="col">N° Téléphone</th>
                <th scope="col">Adresse e-mail</th>
                <th scope="col">Quantité demandé</th>
                <th scope="col">Date de demande</th>
                <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>